export const API_FETCH_GROUP_BLOCK = 'API_FETCH_GROUP_BLOCK';
export const API_ADD_GROUP = 'API_ADD_GROUP';
export const API_ADD_BLOCK = 'API_ADD_BLOCK';
export const API_UPDATE_NAME_GROUP = 'API_UPDATE_NAME_GROUP';
export const API_UPDATE_NAME_BLOCK = 'API_UPDATE_NAME_BLOCK';
export const API_DELETE_GROUP = 'API_DELETE_GROUP';
export const API_DELETE_BLOCK = 'API_DELETE_BLOCK';

export const FETCH_BLOCK = 'FETCH_BLOCK';
export const ADD_BLOCK = 'ADD_BLOCK';
export const ADD_GROUP = 'ADD_GROUP';
export const UPDATE_NAME_GROUP = 'UPDATE_NAME_GROUP';
export const UPDATE_NAME_BLOCK = 'UPDATE_NAME_BLOCK';
export const DELETE_GROUP = 'DELETE_GROUP';
export const DELETE_BLOCK = 'DELETE_BLOCK';

export const API_FETCH_ELEMENT = 'API_FETCH_ELEMENT';
export const FETCH_ELEMENT = 'FETCH_ELEMENT';

export const API_ADD_ELEMENT = 'API_ADD_ELEMENT';
export const ADD_ELEMENT = 'ADD_ELEMENT';

export const API_UPLOAD_IMAGE = 'API_UPLOAD_IMAGE';
export const UPLOAD_SUCCESS = 'UPLOAD_SUCCESS';

export const API_UPLOAD_CARD = 'API_UPLOAD_CARD';
export const UPLOAD_CARD_SUCCESS = 'UPLOAD_CARD_SUCCESS';

export const CHANGE_VALUE_ELEMENT = 'CHANGE_VALUE_ELEMENT';

export const API_UPDATE_ELEMENT = 'API_UPDATE_ELEMENT';
export const UPDATE_ELEMENT = 'UPDATE_ELEMENT';

export const CHANGE_OPTION = 'CHANGE_OPTION';

export const API_DELETE_ELEMENT = 'API_DELETE_ELEMENT';
export const DELETE_ELEMENT = 'DELETE_ELEMENT';

export const SEARCH_BLOCK = 'SEARCH_BLOCK';
