export const API_GET_DATA_BOT = 'API_GET_DATA_BOT';
export const GET_DATA_BOT = 'GET_DATA_BOT';


export const FETCH_BOT = 'FETCH_BOT';
export const FETCH_BOT_SUCCESS = 'FETCH_BOT_SUCCESS';
export const FETCH_BOT_FAILED = 'FETCH_BOT_FAILED';

export const DELETE_BOT = 'DELETE_BOT';
export const DELETE_BOT_SUCCESS = 'DELETE_BOT_SUCCESS';
export const DELETE_BOT_FAILD = 'DELETE_BOT_FAILED';
export const DELETE_CONFIRM = 'DELETE_CONFIRM';

