export const API_FETCH_RULE = 'CALL_API_FETCH_RULE';
export const FETCH_RULE_SUCCESS = 'FETCH_RULE_SUCCESS';

export const API_ADD_RULE = 'CALL_API_ADD_RULE';
export const ADD_RULE_SUCCESS = 'ADD_RULE_SUCCESS';

export const API_UPDATE_RULE = 'CALL_API_UPDATE_RULE';
export const UPDATE_RULE_SECCESS = 'UPDATE_RULE_SECCESS';

export const API_DELETE_RULE = 'CALL_API_DELETE_RULE';
export const DELETE_RULE_SECCESS = 'DELETE_RULE_SECCESS';

export const SEARCH_RULE = 'SEARCH_RULE';
