const useStyles = () => ({
    root: {
        flexGrow: 1,
        fontFamily: 'Montserrat',
        top: ' 0',
        bottom: '0',
        padding: '8px 16px',
        position: 'absolute',
        overflowY: 'scroll',
        backgroundColor: '#f3f3f3',
        width: '100%',
    },
    imageCover: {
        width: '100%',
        height: '200px',
    },
    imageAvatar: {
        display: 'inline-block',
        padding: '5px',
        borderRadius: '50%',
        position: 'absolute',
        left: '50%',
        transform: 'translate(-50%, -100px)',
        border: '1px solid #909090',
        backgroundColor: '#ffffff',
        width: '168px',
        height: '168px',
    },
    imageAvatarTag: {
        width: '100%',
        height: 'auto',
        display: 'inline-block',
        borderRadius: '50%',
        boxShadow: ' 0px 0px 10px 3px rgba(122,122,122,1)',
    },
    nameBot: {
        fontSize: '24px',
        fontWeight: 600,
        textAlign: 'center',
        paddingTop: '75px',
    },
    oaId: {
        textAlign: 'center',
        fontSize: '12px',
        marginBottom: '20px',
        textDecoration: 'underline',
    },
    description: { linlineHeight: 2 },
    row: { height: '50%', textAlign: 'center' },
    cell: {},
    title: { fontSize: '20px', margin: '30px auto' },
    number: { fontSize: '32px' },
});
export default useStyles;
